### ISSUE TITLE
apparmor incorrectly purged and rsyslog stops working because of apprmor botch.

### ISSUE THREAD

**Issue by un1versal** [bramvanoploo/xbmc-ubuntu-minimal#4]
The current code need updating to this:

https://github.com/uNiversaI/xbmc-ubuntu-minimal/commit/1f24b60e1a963604596d1e2d92a63a28723abf06

And a proper rsyslog.conf need to made and inserted, please update script so it pulls in the file in https://github.com/uNiversaI/xbmc-ubuntu-minimal/commit/b6ae2910b007707d855e30ab8e347f2d16eddacc
I havent done that, and am unsure how-to.

the path of file is /etc/init/rsyslog.conf

**Comment by bramvanoploo** [comment]
I've applied the suggested patches to the script. I haven't had the chance to test them though. I'll do that later on.

**Comment by un1versal** [comment]
Thanks, let me know if it works, atm this is exactly what I have for proper apparmor removal and rsyslog service fix. Just not sure how to backup local file and download the new one with the script methods.

**Comment by un1versal** [comment]
Have you tested this any further? On my side its working just needs confirmation.

**Comment by un1versal** [comment]
invalid after reply
